### ISSUE TITLE
License of this project ?

### ISSUE THREAD

**Issue by jeanphilipper** [Pingren/bpmn-dataflow-diagram-editor#2]
Hello, I would like to know which license do you use for this project ? (You did not provide any license currently)
I would like to use your code as base for a scholar project, so license is important for the future.

Thanks in advance

**Comment by pingren** [comment]
@jeanphilipper 

This project is MIT licensed. If license is important to you, maybe you should also check bpmn-js license.

https://forum.bpmn.io/t/license-questions/85
